//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: auth.proto
namespace message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CGLogin")]
  public partial class CGLogin : global::ProtoBuf.IExtensible
  {
    public CGLogin() {}
    
    private string _deviceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deviceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deviceId
    {
      get { return _deviceId; }
      set { _deviceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}