//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: map.proto
namespace message
{
    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CGAround")]
    public partial class CGAround : global::ProtoBuf.IExtensible
    {
        public CGAround() { }

        private message.Location _gpsLocation;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"gpsLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location gpsLocation
        {
            get { return _gpsLocation; }
            set { _gpsLocation = value; }
        }
        private readonly global::System.Collections.Generic.List<message.POIType> _types = new global::System.Collections.Generic.List<message.POIType>();
        [global::ProtoBuf.ProtoMember(2, Name = @"types", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<message.POIType> types
        {
            get { return _types; }
        }


        private int _radius = default(int);
        [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name = @"radius", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        [global::System.ComponentModel.DefaultValue(default(int))]
        public int radius
        {
            get { return _radius; }
            set { _radius = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"Location")]
    public partial class Location : global::ProtoBuf.IExtensible
    {
        public Location() { }

        private string _longitude;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"longitude", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string longitude
        {
            get { return _longitude; }
            set { _longitude = value; }
        }
        private string _latitude;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"latitude", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string latitude
        {
            get { return _latitude; }
            set { _latitude = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GCAroundInfo")]
    public partial class GCAroundInfo : global::ProtoBuf.IExtensible
    {
        public GCAroundInfo() { }

        private message.Location _mapLocation;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"mapLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location mapLocation
        {
            get { return _mapLocation; }
            set { _mapLocation = value; }
        }
        private string _cityName;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"cityName", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string cityName
        {
            get { return _cityName; }
            set { _cityName = value; }
        }
        private string _cityCode;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"cityCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string cityCode
        {
            get { return _cityCode; }
            set { _cityCode = value; }
        }
        private global::System.Collections.Generic.List<message.POIData> _poiData = new global::System.Collections.Generic.List<message.POIData>();
        [global::ProtoBuf.ProtoMember(4, Name = @"poiData", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<message.POIData> poiData
        {
            get { return _poiData; }
            set { _poiData = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"POIData")]
    public partial class POIData : global::ProtoBuf.IExtensible
    {
        public POIData() { }

        private string _id;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string id
        {
            get { return _id; }
            set { _id = value; }
        }
        private string _name;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }

        private string _name_py;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"name_py", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name_py
        {
            get { return _name_py; }
            set { _name_py = value; }
        }

        private string _type;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string type
        {
            get { return _type; }
            set { _type = value; }
        }


        private string _type_py;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"type_py", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string type_py
        {
            get { return _type_py; }
            set { _type_py = value; }
        }

        private string _typecode;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"typecode", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string typecode
        {
            get { return _typecode; }
            set { _typecode = value; }
        }

        private string _biz_type = "";
        [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name = @"biz_type", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string biz_type
        {
            get { return _biz_type; }
            set { _biz_type = value; }
        }
        private string _address;
        [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name = @"address", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string address
        {
            get { return _address; }
            set { _address = value; }
        }
        private message.Location _location;
        [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name = @"location", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location location
        {
            get { return _location; }
            set { _location = value; }
        }

        private string _tel = "";
        [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name = @"tel", DataFormat = global::ProtoBuf.DataFormat.Default)]
        [global::System.ComponentModel.DefaultValue("")]
        public string tel
        {
            get { return _tel; }
            set { _tel = value; }
        }
        private int _distance;
        [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name = @"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int distance
        {
            get { return _distance; }
            set { _distance = value; }
        }
        private string _rating;
        [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name = @"rating", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string rating
        {
            get { return _rating; }
            set { _rating = value; }
        }
        private int _isAR;
        [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name = @"isAR", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int isAR
        {
            get { return _isAR; }
            set { _isAR = value; }
        }
        private string _desc;
        [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name = @"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string desc
        {
            get { return _desc; }
            set { _desc = value; }
        }
        private string _iconImage;
        [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name = @"iconImage", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string iconImage
        {
            get { return _iconImage; }
            set { _iconImage = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GCTypesDefaultInfo")]
    public partial class GCTypesDefaultInfo : global::ProtoBuf.IExtensible
    {
        public GCTypesDefaultInfo() { }

        private readonly global::System.Collections.Generic.List<message.POIType> _poiType = new global::System.Collections.Generic.List<message.POIType>();
        [global::ProtoBuf.ProtoMember(1, Name = @"poiType", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<message.POIType> poiType
        {
            get { return _poiType; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"POIType")]
    public partial class POIType : global::ProtoBuf.IExtensible
    {
        public POIType() { }

        private string _code;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string code
        {
            get { return _code; }
            set { _code = value; }
        }
        private string _name;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string name
        {
            get { return _name; }
            set { _name = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"CGDirectionWalk")]
    public partial class CGDirectionWalk : global::ProtoBuf.IExtensible
    {
        public CGDirectionWalk() { }

        private message.Location _originGpsLocation;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"originGpsLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location originGpsLocation
        {
            get { return _originGpsLocation; }
            set { _originGpsLocation = value; }
        }
        private message.Location _destinationLocation;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"destinationLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location destinationLocation
        {
            get { return _destinationLocation; }
            set { _destinationLocation = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"GCDirectionWalkInfo")]
    public partial class GCDirectionWalkInfo : global::ProtoBuf.IExtensible
    {
        public GCDirectionWalkInfo() { }

        private message.DirectionWalkingRoute _directionWalkingRoute;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"directionWalkingRoute", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.DirectionWalkingRoute directionWalkingRoute
        {
            get { return _directionWalkingRoute; }
            set { _directionWalkingRoute = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DirectionWalkingRoute")]
    public partial class DirectionWalkingRoute : global::ProtoBuf.IExtensible
    {
        public DirectionWalkingRoute() { }

        private message.Location _originLocation;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"originLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location originLocation
        {
            get { return _originLocation; }
            set { _originLocation = value; }
        }
        private message.Location _destinationLocation;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"destinationLocation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public message.Location destinationLocation
        {
            get { return _destinationLocation; }
            set { _destinationLocation = value; }
        }
        private global::System.Collections.Generic.List<message.DirectionWalkingPath> _path = new global::System.Collections.Generic.List<message.DirectionWalkingPath>();
        [global::ProtoBuf.ProtoMember(3, Name = @"path", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<message.DirectionWalkingPath> path
        {
            get { return _path; }
            set { _path = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DirectionWalkingPath")]
    public partial class DirectionWalkingPath : global::ProtoBuf.IExtensible
    {
        public DirectionWalkingPath() { }

        private int _distance;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int distance
        {
            get { return _distance; }
            set { _distance = value; }
        }
        private int _duration;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int duration
        {
            get { return _duration; }
            set { _duration = value; }
        }
        private global::System.Collections.Generic.List<message.DirectionWalkingStep> _step = new global::System.Collections.Generic.List<message.DirectionWalkingStep>();
        [global::ProtoBuf.ProtoMember(3, Name = @"step", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<message.DirectionWalkingStep> step
        {
            get { return _step; }
            set { _step = value; }
        }

        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

    [global::System.Serializable, global::ProtoBuf.ProtoContract(Name = @"DirectionWalkingStep")]
    public partial class DirectionWalkingStep : global::ProtoBuf.IExtensible
    {
        public DirectionWalkingStep() { }

        private string _instruction;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"instruction", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string instruction
        {
            get { return _instruction; }
            set { _instruction = value; }
        }

        private string _instruction1;
        [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name = @"instruction1", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string instruction1
        {
            get { return _instruction1; }
            set { _instruction1 = value; }
        }

        private string _road;
        [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name = @"road", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string road
        {
            get { return _road; }
            set { _road = value; }
        }
        private int _distance;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"distance", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int distance
        {
            get { return _distance; }
            set { _distance = value; }
        }

        private int _distanceall;
        [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name = @"distanceall", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int distanceall
        {
            get { return _distanceall; }
            set { _distanceall = value; }
        }
        private string _orientation;
        [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name = @"orientation", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string orientation
        {
            get { return _orientation; }
            set { _orientation = value; }
        }
        private int _duration;
        [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name = @"duration", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
        public int duration
        {
            get { return _duration; }
            set { _duration = value; }
        }
        private global::System.Collections.Generic.List<message.Location> _polyline = new global::System.Collections.Generic.List<message.Location>();
        [global::ProtoBuf.ProtoMember(6, Name = @"polyline", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public global::System.Collections.Generic.List<message.Location> polyline
        {
            get { return _polyline; }
            set { _polyline = value; }
        }

        private string _action;
        [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name = @"action", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string action
        {
            get { return _action; }
            set { _action = value; }
        }
        private string _assistant_action;
        [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name = @"assistant_action", DataFormat = global::ProtoBuf.DataFormat.Default)]
        public string assistant_action
        {
            get { return _assistant_action; }
            set { _assistant_action = value; }
        }
        private global::ProtoBuf.IExtension extensionObject;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    }

}